# Site settings
title: Tweet Awareness
email: adrian.loewenstein@epfl.ch
url: https://tweet-awareness.eu
description: "Can we predict awareness to specific events in different countries around the globe ? \n Can we model the awareness using cultural metrics or simply using distance metrics between countries?"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: 'FloralWhite '
  links: '#219ab3'

# Footer settings
footer: Tweet Awareness

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
permalink: pretty
