# Site settings
title: Tweet Awareness
email: adrian.loewenstein@icloud.com
description: "Can we model awareness to specific events in different countries around the globe ? \n Can we predict the levels of reactions on social media using cultural metrics or simply using distance metrics between countries?"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: 'FloralWhite '
  links: '#219ab3'

# Footer settings
footer: Tweet Awareness

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
permalink: pretty
